"""Add entity fields to transactions

Revision ID: 34c14d880d29
Revises: 5b9eed74f11b
Create Date: 2026-08-21 13:16:37.199492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c14d880d29'
down_revision: Union[str, Sequence[str], None] = '5b9eed74f11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_id', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('merchant_id', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('ip_hash', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('geo_region', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_ip_hash'), 'transactions', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ip_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_column('transactions', 'geo_region')
    op.drop_column('transactions', 'ip_hash')
    op.drop_column('transactions', 'device_id')
    op.drop_column('transactions', 'merchant_id')
    op.drop_column('transactions', 'customer_id')
    # ### end Alembic commands ###
