"""Update Investigation model for AI Agent

Revision ID: 59584782fb07
Revises: 34c14d880d29
Create Date: 2026-08-22 09:34:33.885489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59584782fb07'
down_revision: Union[str, Sequence[str], None] = '34c14d880d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('status', sa.String(), nullable=False))
    op.add_column('investigations', sa.Column('severity', sa.String(), nullable=True))
    op.alter_column('investigations', 'reasoning',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='reasoning::jsonb',
               existing_nullable=True)
    op.alter_column('investigations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investigations', 'confidence',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('investigations', 'reasoning',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('investigations', 'severity')
    op.drop_column('investigations', 'status')
    # ### end Alembic commands ###
